import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { AIWIKI_VERSION, INDEX_PATH } from "./constants.js";
import { resolveProjectPath } from "./paths.js";
import type { AIWikiConfig, WikiPage } from "./types.js";
import { scanWikiPages } from "./wiki-store.js";

function titleForPage(page: WikiPage): string {
  if (page.frontmatter.title && page.frontmatter.title.trim().length > 0) {
    return page.frontmatter.title;
  }

  const heading = page.body
    .split("\n")
    .find((line) => line.trim().startsWith("#"));

  return heading ? heading.replace(/^#+\s*/u, "").trim() : page.relativePath;
}

function wikiLink(page: WikiPage): string {
  return `[[wiki/${page.relativePath}]]`;
}

function formatIndexSection(
  title: string,
  pages: WikiPage[],
  fallback: string
): string {
  const lines = pages.map((page) => `- ${wikiLink(page)} - ${titleForPage(page)}`);
  return `## ${title}\n\n${lines.length > 0 ? lines.join("\n") : `- ${fallback}`}`;
}

export function formatWikiIndex(config: AIWikiConfig, pages: WikiPage[]): string {
  const sorted = [...pages].sort((a, b) => a.relativePath.localeCompare(b.relativePath));
  const byType = (type: string) =>
    sorted.filter((page) => page.frontmatter.type === type);

  return [
    `# AIWiki Index: ${config.projectName}`,
    "",
    "This index is maintained by AIWiki commands.",
    "",
    `Generated by AIWiki ${AIWIKI_VERSION}.`,
    "",
    formatIndexSection("Project Map", byType("project_map"), "No project map has been generated yet."),
    "",
    formatIndexSection("Modules", byType("module"), "No module pages yet."),
    "",
    formatIndexSection("Pitfalls", byType("pitfall"), "No pitfall pages yet."),
    "",
    formatIndexSection("Decisions", byType("decision"), "No decision pages yet."),
    "",
    formatIndexSection("Patterns", byType("pattern"), "No pattern pages yet."),
    "",
    formatIndexSection("Rules", byType("rule"), "No rule pages yet.")
  ].join("\n").trimEnd() + "\n";
}

export async function regenerateIndex(
  rootDir: string,
  config: AIWikiConfig
): Promise<void> {
  const pages = await scanWikiPages(rootDir);
  const indexPath = resolveProjectPath(rootDir, INDEX_PATH);
  await mkdir(path.dirname(indexPath), { recursive: true });
  await writeFile(indexPath, formatWikiIndex(config, pages), "utf8");
}
